# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    default_locale: fr

    # Note that the session will be started ONLY if you read or write from it.
    session: 
        # "auto" => Secure seulement quand la requête est en HTTPS
        cookie_secure: auto
        # Lax est un bon compromis pour une app classique (login + pages)
        cookie_samesite: lax
        # Bon réflexe : JS ne peut pas lire le cookie de session
        cookie_httponly: true
        cookie_lifetime: 0

    serializer:
        enabled: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
