---
# Production environment override
services:
  php:
    build:
      context: .
      target: frankenphp_prod
    env_file:
      - path: .env.prod.local
        required: false
    environment:
      APP_ENV: prod
      SERVER_NAME: "nidemiel.com"
    volumes:
      - uploads_data:/app/public/assets/images
      - videos_data:/app/public/assets/videos

  messenger-worker:
    env_file:
      - path: .env.prod.local
        required: false
    environment:
      APP_ENV: prod

  database:
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - .env
      - path: .env.prod.local
        required: false

volumes:
  uploads_data:
  videos_data:
