<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260119150214 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE product_variant (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label VARCHAR(60) NOT NULL, sku VARCHAR(80) NOT NULL, price_cents INT NOT NULL, in_stock BOOLEAN DEFAULT true NOT NULL, product_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_209AA41DF9038C4 ON product_variant (sku)');
        $this->addSql('CREATE INDEX IDX_209AA41D4584665A ON product_variant (product_id)');
        $this->addSql('ALTER TABLE product_variant ADD CONSTRAINT FK_209AA41D4584665A FOREIGN KEY (product_id) REFERENCES product (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product ADD origin_country VARCHAR(80) DEFAULT NULL');
        $this->addSql('ALTER TABLE product ADD seo_title VARCHAR(70) DEFAULT NULL');
        $this->addSql('ALTER TABLE product ADD seo_description VARCHAR(170) DEFAULT NULL');
        $this->addSql('ALTER TABLE product ADD seo_noindex BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE product ADD seo_og_image VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE product ADD seo_canonical_override VARCHAR(255) DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE product_variant DROP CONSTRAINT FK_209AA41D4584665A');
        $this->addSql('DROP TABLE product_variant');
        $this->addSql('ALTER TABLE product DROP origin_country');
        $this->addSql('ALTER TABLE product DROP seo_title');
        $this->addSql('ALTER TABLE product DROP seo_description');
        $this->addSql('ALTER TABLE product DROP seo_noindex');
        $this->addSql('ALTER TABLE product DROP seo_og_image');
        $this->addSql('ALTER TABLE product DROP seo_canonical_override');
    }
}
