<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260429194427 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE product_lot (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, lot_number VARCHAR(50) NOT NULL, received_at DATE NOT NULL, expires_at DATE DEFAULT NULL, is_current BOOLEAN DEFAULT false NOT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, product_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EBAE7D044584665A ON product_lot (product_id)');
        $this->addSql('ALTER TABLE product_lot ADD CONSTRAINT FK_EBAE7D044584665A FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE product_lot DROP CONSTRAINT FK_EBAE7D044584665A');
        $this->addSql('DROP TABLE product_lot');
    }
}
