<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260120081222 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE product_variant DROP CONSTRAINT fk_209aa41d4584665a');
        $this->addSql('DROP TABLE product_variant');
        $this->addSql('ALTER TABLE product ADD weight_grams INT DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE product_variant (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label VARCHAR(60) NOT NULL, sku VARCHAR(80) NOT NULL, price_cents INT NOT NULL, in_stock BOOLEAN DEFAULT true NOT NULL, product_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_209aa41df9038c4 ON product_variant (sku)');
        $this->addSql('CREATE INDEX idx_209aa41d4584665a ON product_variant (product_id)');
        $this->addSql('ALTER TABLE product_variant ADD CONSTRAINT fk_209aa41d4584665a FOREIGN KEY (product_id) REFERENCES product (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE product DROP weight_grams');
    }
}
