<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260420204648 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE faq ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE faq ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE faq ALTER position DROP DEFAULT');
        $this->addSql('ALTER TABLE faq ALTER is_active DROP DEFAULT');
        $this->addSql('ALTER TABLE sliders ALTER button_text DROP NOT NULL');
        $this->addSql('ALTER TABLE sliders ALTER button_link DROP NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE faq ALTER id SET DEFAULT nextval(\'faq_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE faq ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE faq ALTER "position" SET DEFAULT 0');
        $this->addSql('ALTER TABLE faq ALTER is_active SET DEFAULT true');
        $this->addSql('ALTER TABLE sliders ALTER button_text SET NOT NULL');
        $this->addSql('ALTER TABLE sliders ALTER button_link SET NOT NULL');
    }
}
