<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260106204227 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE payment_method (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, more_description TEXT DEFAULT NULL, test_public_api_key TEXT DEFAULT NULL, test_private_api_key TEXT DEFAULT NULL, prod_public_api_key TEXT DEFAULT NULL, prod_private_api_key TEXT DEFAULT NULL, test_base_url TEXT DEFAULT NULL, prod_base_url TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE media ADD payment_method_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE media ADD CONSTRAINT FK_6A2CA10C5AA1164F FOREIGN KEY (payment_method_id) REFERENCES category (id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6A2CA10C5AA1164F ON media (payment_method_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE payment_method');
        $this->addSql('ALTER TABLE media DROP CONSTRAINT FK_6A2CA10C5AA1164F');
        $this->addSql('DROP INDEX UNIQ_6A2CA10C5AA1164F');
        $this->addSql('ALTER TABLE media DROP payment_method_id');
    }
}
