<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260406070440 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE carrier ADD type VARCHAR(50) DEFAULT \'manual\' NOT NULL');
        $this->addSql('ALTER TABLE carrier ADD delivery_delay VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE carrier ADD has_pickup_points BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE invoice ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE invoice ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE invoice ALTER status DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN invoice.issued_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN invoice.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN invoice.updated_at IS \'\'');
        $this->addSql("DO \$\$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'uniq_invoice_number') THEN ALTER INDEX uniq_invoice_number RENAME TO UNIQ_906517442DA68207; END IF; END \$\$");
        $this->addSql("DO \$\$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'uniq_invoice_order') THEN ALTER INDEX uniq_invoice_order RENAME TO UNIQ_90651744A15A2E17; END IF; END \$\$");
        $this->addSql('COMMENT ON COLUMN "order".stock_decremented_at IS \'\'');
        $this->addSql('ALTER TABLE shipment ADD label_url VARCHAR(512) DEFAULT NULL');
        $this->addSql('ALTER TABLE shipment ADD weight_grams INT DEFAULT NULL');
        $this->addSql('ALTER TABLE shipment ADD status_code VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE shipment ADD synced_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE shipment ADD error_message TEXT DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE carrier DROP type');
        $this->addSql('ALTER TABLE carrier DROP delivery_delay');
        $this->addSql('ALTER TABLE carrier DROP has_pickup_points');
        $this->addSql('ALTER TABLE invoice ALTER id SET DEFAULT nextval(\'invoice_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE invoice ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE invoice ALTER status SET DEFAULT \'draft\'');
        $this->addSql('COMMENT ON COLUMN invoice.issued_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN invoice.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN invoice.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER INDEX uniq_906517442da68207 RENAME TO uniq_invoice_number');
        $this->addSql('ALTER INDEX uniq_90651744a15a2e17 RENAME TO uniq_invoice_order');
        $this->addSql('COMMENT ON COLUMN "order".stock_decremented_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE shipment DROP label_url');
        $this->addSql('ALTER TABLE shipment DROP weight_grams');
        $this->addSql('ALTER TABLE shipment DROP status_code');
        $this->addSql('ALTER TABLE shipment DROP synced_at');
        $this->addSql('ALTER TABLE shipment DROP error_message');
    }
}
