<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260112203942 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE stripe_webhook_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, stripe_event_id VARCHAR(255) NOT NULL, type VARCHAR(100) NOT NULL, received_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_stripe_event_id ON stripe_webhook_event (stripe_event_id)');
        $this->addSql('ALTER TABLE setting ADD free_shipping_threshold_cents INT DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE stripe_webhook_event');
        $this->addSql('ALTER TABLE setting DROP free_shipping_threshold_cents');
    }
}
