<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260106195244 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE wishlist (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, customer_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9CE12A319395C3F3 ON wishlist (customer_id)');
        $this->addSql('CREATE TABLE wishlist_product (wishlist_id INT NOT NULL, product_id INT NOT NULL, PRIMARY KEY (wishlist_id, product_id))');
        $this->addSql('CREATE INDEX IDX_4C46D2D7FB8E54CD ON wishlist_product (wishlist_id)');
        $this->addSql('CREATE INDEX IDX_4C46D2D74584665A ON wishlist_product (product_id)');
        $this->addSql('ALTER TABLE wishlist ADD CONSTRAINT FK_9CE12A319395C3F3 FOREIGN KEY (customer_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE wishlist_product ADD CONSTRAINT FK_4C46D2D7FB8E54CD FOREIGN KEY (wishlist_id) REFERENCES wishlist (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE wishlist_product ADD CONSTRAINT FK_4C46D2D74584665A FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE wishlist DROP CONSTRAINT FK_9CE12A319395C3F3');
        $this->addSql('ALTER TABLE wishlist_product DROP CONSTRAINT FK_4C46D2D7FB8E54CD');
        $this->addSql('ALTER TABLE wishlist_product DROP CONSTRAINT FK_4C46D2D74584665A');
        $this->addSql('DROP TABLE wishlist');
        $this->addSql('DROP TABLE wishlist_product');
    }
}
