<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260115160032 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE shipment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tracking_number VARCHAR(255) NOT NULL, tracking_url VARCHAR(255) NOT NULL, pickup_point_id VARCHAR(255) DEFAULT NULL, pickup_point_name VARCHAR(255) DEFAULT NULL, pickup_point_address VARCHAR(255) DEFAULT NULL, pickup_point_postal_code VARCHAR(20) DEFAULT NULL, pickup_point_city VARCHAR(255) DEFAULT NULL, shipped_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, customer_order_id INT DEFAULT NULL, carrier_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2CB20DCA15A2E17 ON shipment (customer_order_id)');
        $this->addSql('CREATE INDEX IDX_2CB20DC21DFC797 ON shipment (carrier_id)');
        $this->addSql('CREATE TABLE shipment_status (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status_code VARCHAR(255) NOT NULL, label VARCHAR(255) NOT NULL, occured_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, raw_data JSON DEFAULT NULL, shipment_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DD30FFD97BE036FC ON shipment_status (shipment_id)');
        $this->addSql('ALTER TABLE shipment ADD CONSTRAINT FK_2CB20DCA15A2E17 FOREIGN KEY (customer_order_id) REFERENCES "order" (id)');
        $this->addSql('ALTER TABLE shipment ADD CONSTRAINT FK_2CB20DC21DFC797 FOREIGN KEY (carrier_id) REFERENCES carrier (id)');
        $this->addSql('ALTER TABLE shipment_status ADD CONSTRAINT FK_DD30FFD97BE036FC FOREIGN KEY (shipment_id) REFERENCES shipment (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE shipment DROP CONSTRAINT FK_2CB20DCA15A2E17');
        $this->addSql('ALTER TABLE shipment DROP CONSTRAINT FK_2CB20DC21DFC797');
        $this->addSql('ALTER TABLE shipment_status DROP CONSTRAINT FK_DD30FFD97BE036FC');
        $this->addSql('DROP TABLE shipment');
        $this->addSql('DROP TABLE shipment_status');
    }
}
