<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260117004925 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE blog (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT NOT NULL, image VARCHAR(255) NOT NULL, is_published BOOLEAN NOT NULL, slug VARCHAR(255) NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE blog_media (blog_id INT NOT NULL, media_id INT NOT NULL, PRIMARY KEY (blog_id, media_id))');
        $this->addSql('CREATE INDEX IDX_9AC3E2C4DAE07E97 ON blog_media (blog_id)');
        $this->addSql('CREATE INDEX IDX_9AC3E2C4EA9FDD75 ON blog_media (media_id)');
        $this->addSql('ALTER TABLE blog_media ADD CONSTRAINT FK_9AC3E2C4DAE07E97 FOREIGN KEY (blog_id) REFERENCES blog (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE blog_media ADD CONSTRAINT FK_9AC3E2C4EA9FDD75 FOREIGN KEY (media_id) REFERENCES media (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE blog_media DROP CONSTRAINT FK_9AC3E2C4DAE07E97');
        $this->addSql('ALTER TABLE blog_media DROP CONSTRAINT FK_9AC3E2C4EA9FDD75');
        $this->addSql('DROP TABLE blog');
        $this->addSql('DROP TABLE blog_media');
    }
}
