<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260425100605 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE wholesale_tier (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, min_qty_kg INT NOT NULL, label VARCHAR(80) DEFAULT NULL, unit_price_cents INT NOT NULL, product_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_43F6A6024584665A ON wholesale_tier (product_id)');
        $this->addSql('ALTER TABLE wholesale_tier ADD CONSTRAINT FK_43F6A6024584665A FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product ADD is_wholesale_available BOOLEAN DEFAULT NULL');
        $this->addSql('ALTER TABLE product ADD wholesale_min_qty_kg INT DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE wholesale_tier DROP CONSTRAINT FK_43F6A6024584665A');
        $this->addSql('DROP TABLE wholesale_tier');
        $this->addSql('ALTER TABLE product DROP is_wholesale_available');
        $this->addSql('ALTER TABLE product DROP wholesale_min_qty_kg');
    }
}
